### ISSUE TITLE
Kong Dashboard  on kubernetes

### ISSUE THREAD

**Issue by veris-neerajdhiman** [PGBI/kong-dashboard#107]
- Is their anyway we can set-up this `kong-dashboard` on kubernetes. 
- I tried the same but since it will be set up in different container then it will not linked with kong setup on different container.
- I have managed to setup kong on kubernetes using [kong-dist-kubernetes
](https://github.com/Mashape/kong-dist-kubernetes/blob/master/kong_cassandra.yaml )

**Comment by perryao** [comment]
I have this running on kubernetes with the following: 

```
apiVersion: v1
kind: Service
metadata:
  name: kong-dashboard
spec:
  type: LoadBalancer
  loadBalancerSourceRanges:
    - 0.0.0.0/0
  ports:
    - name: kong-dashboard
      port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: kong-dashboard

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kong-dashboard
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: kong-dashboard
        app: kong-dashboard
    spec:
      containers:
        - name: kong-dashboard
          image: pgbi/kong-dashboard
          args: ["start", "--kong-url", "http://kong-admin:8001"]
          ports:
            - name: main
              containerPort: 8080
              protocol: TCP
```

Run `kubectl create -f kong-dashboard.yaml` to deploy a service and deployment.

update your `args` if your kong service isn't at kong-admin.

**Comment by dynastymasra** [comment]
@perryao there kong dashboard have open endpoint for healthcheck?
if active basic auth google healthcheck will get error 401

**Comment by PGBI** [comment]
@dynastymasra Since https://github.com/PGBI/kong-dashboard/pull/146 has been merged, there is an healthcheck endpoint that returns 200 even when kong-dashboard requires authentication: `GET /healthz`

**Comment by dynastymasra** [comment]
thank you @PGBI about this info, i test it works fine

**Comment by azhar-mohammed** [comment]
@PGBI How to enable basic authentication on kong-dashboard iam trying to use it along with kubernetes.

**Comment by dynastymasra** [comment]
@azhar-mohammed you can insert command `-basic-auth user1=password1 user2=password2
` in kubernetes `args`, like ` args: ["-basic-auth user1=password1 user2=password2"]`

**Comment by azhar-mohammed** [comment]
@dynastymasra  thanks

**Comment by Goddywu** [comment]
I have used helm to deploy kong in kubernetes, and a single yaml file to deploy kong-dashboard, like this,
```
---
apiVersion: v1
kind: Service
metadata:
  name: kong-dashboard
  namespace: kong
spec:
  # type: NodePort
  selector:
    app: dashboard
  ports:
  - port: 8080
    protocol: TCP
---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kong-dashboard
  namespace: kong
spec:
  template:
    metadata:
      labels:
        name: dashboard
        app: dashboard
    spec:
      containers:
      - name: kong-dashboard
        args:
        - start
        - --kong-url http://my-kong-kong-admin:8444
        # - --basic-auth admin=admin
        image: pgbi/kong-dashboard:latest
        ports:
        - containerPort: 8080
```
I can see the GUI, and create some consumers and plugins by it, and these do work.
However, I delete kong-dashboard, my data（ consumers and plugins ） is missing.

what happened?    I think the data should be saved in pg, why they are deleted with kong dashboard ??
